[build]

functions = "functions"
included_files = ["**.xlsx"]

[dev]
framework="#static"
functions = "functions"


  # Includes all XLSX files inside the "files/" directory.
  included_files = ["**.xlsx"]