[build]

functions = "functions"
included_files = ["file_example.xlsx"]

  [functions.api] 
  # Includes all XLSX files inside the "files/" directory.
  included_files = ["file_example.xlsx"]

[dev]
framework="#static"
functions = "functions"

