[build]
framework="#static"

[dev]
framework="#static"

[functions]
  # Sets a custom directory for Netlify Functions
  directory = "functions"
  included_files = ["file_example.xlsx"]
  external_node_modules = ["express","xlsx-populate","serverless-http"]